from fpdf import FPDF
import os

# 创建PDF对象
pdf = FPDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

# 注册中文字体
font_paths = [
    'C:/Windows/Fonts/msyh.ttc',      # 微软雅黑
    'C:/Windows/Fonts/simsun.ttc',    # 宋体
    'C:/Windows/Fonts/simhei.ttf',    # 黑体
    '/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc', # Linux常见字体
    '/System/Library/Fonts/PingFang.ttc' # macOS常见字体
]
font_path = None
for fp in font_paths:
    if os.path.exists(fp):
        font_path = fp
        break

if font_path:
    pdf.add_font('ChineseFont', '', font_path, uni=True)
    pdf.set_font('ChineseFont', '', 12)
else:
    pdf.set_font('Arial', '', 12)

# 定义颜色
BG_COLOR = (245, 247, 250)    # 浅灰背景
HEADER_COLOR = (33, 37, 41)    # 深灰/黑
CARD_BG = (255, 255, 255)      # 白色卡片
ACCENT_1 = (59, 130, 246)     # 蓝色 (Chat)
ACCENT_2 = (16, 185, 129)     # 绿色 (Work)
ACCENT_3 = (139, 92, 246)     # 紫色 (Codex)
TEXT_COLOR = (33, 33, 33)      # 深灰文字
SUBTEXT_COLOR = (100, 100, 100) # 浅灰文字

# 辅助函数：绘制圆角矩形
def draw_rounded_rect(pdf, x, y, w, h, r, style='F', color=None):
    if color:
        pdf.set_fill_color(*color)
    else:
        pdf.set_fill_color(*CARD_BG)
    
    # 简单模拟圆角，实际fpdf2对复杂路径支持有限，这里用标准矩形加阴影或边框模拟
    # 为了简洁和兼容性，使用标准矩形，但设置较好的边框和填充
    pdf.rect(x, y, w, h, style)
    
    # 如果需要更高级的圆角，通常需要使用绘图扩展，这里保持基础兼容性
    # 通过绘制细线边框来增强卡片感
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.5)
    pdf.rect(x + 0.5, y + 0.5, w - 1, h - 1)

# 辅助函数：绘制图标（使用Unicode字符模拟）
def draw_icon(pdf, icon_char, x, y, size=16, color=None):
    if color:
        pdf.set_text_color(*color)
    pdf.set_font('ChineseFont', '', size)
    pdf.text(x, y + size, icon_char)

# 标题部分
pdf.set_fill_color(*HEADER_COLOR)
pdf.rect(0, 0, pdf.w, 40, 'F')
pdf.set_text_color(255, 255, 255)
pdf.set_font('ChineseFont', '', 18)
pdf.cell(0, 40, 'AI 全能助手能力图谱', ln=True, align='C')

# 布局参数
margin_left = 20
margin_right = 20
top_margin = 50
card_height = 180
card_width = (pdf.w - margin_left - margin_right - 40) / 3 # 40为间距
col_gap = 20

# 列定义
columns = [
    {"title": "Chat", "subtitle": "对话与创作", "icon": "💬", "color": ACCENT_1, "keywords": ["智能问答", "文案写作", "润色改写"]},
    {"title": "Work", "subtitle": "办公与效率", "icon": "💼", "color": ACCENT_2, "keywords": ["简报生成", "邮件起草", "表格处理"]},
    {"title": "Codex", "subtitle": "代码与开发", "icon": "💻", "color": ACCENT_3, "keywords": ["代码生成", "项目辅助", "自动化脚本"]}
]

for i, col in enumerate(columns):
    x = margin_left + i * (card_width + col_gap)
    y = top_margin
    
    # 1. 绘制卡片背景
    draw_rounded_rect(pdf, x, y, card_width, card_height, 5, 'D', col['color'])
    
    # 2. 顶部标题栏背景
    pdf.set_fill_color(*col['color'])
    pdf.rect(x, y, card_width, 40, 'F')
    
    # 3. 标题文字
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('ChineseFont', '', 14)
    pdf.text(x + 10, y + 16, col['icon']) # 图标
    pdf.text(x + 25, y + 16, col['title'])
    
    pdf.set_font('ChineseFont', '', 10)
    pdf.cell(0, 12, col['subtitle'], ln=False, align='L') # 子标题在标题下方
    
    # 4. 关键词列表
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font('ChineseFont', '', 12)
    keyword_y = y + 55
    pdf.set_x(x + 10)
    
    for k_idx, kw in enumerate(col['keywords']):
        # 绘制小圆点
        pdf.set_fill_color(*col['color'])
        pdf.circle(x + 15, keyword_y + 4, 2, 'F')
        
        # 绘制文字
        pdf.text(x + 22, keyword_y + 4, kw)
        keyword_y += 15

# 底部说明
pdf.set_text_color(*SUBTEXT_COLOR)
pdf.set_font('ChineseFont', '', 10)
pdf.ln(20)
pdf.cell(0, 10, 'Generated by AI Assistant', ln=True, align='C')

# 保存文件
output_filename = 'ai_ability_poster.pdf'
pdf.output(output_filename)
print(f"PDF已生成: {output_filename}")